name: CI/CD 

on:
  push:
  pull_request:
    branches: [ master ]

env:
  APP_NAME: ${{ secrets.APP_NAME }}
  FRAMEWORK: ${{ secrets.FRAMEWORK }}
  AZURE_WEBAPP_PACKAGE_PATH: ${{ secerts.AZURE_WEBAPP_PACKAGE_PATH }}
  DOTNET_VERSION: ${{ secrets.DOTNET_VERSION }}

jobs:
  build:
    name: Build - Test - Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: WernerDevOps/devops-actions
        token: ${{ secrets.DEV_BOT_PAT }}
        path: .devops
        ref: create-workflow-template
    - name: Setup .NET
      if: env.FRAMEWORK == 'dotnet-core'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ secrets.DOTNET_VERSION }}
    - name: Build
      uses: "./.devops/common/build"
      with:
        framework: ${{ env.FRAMEWORK }}
    - name: Test
      uses: "./.devops/common/test"
      with:
        framework: ${{ env.FRAMEWORK }}
    - name: Publish
      if: env.FRAMEWORK == 'dotnet-core'
      uses: "./.devops/common/publish"
      if: startsWith(github.ref, 'refs/pull') || github.ref == 'refs/heads/master'
      with:
        framework: ${{ env.FRAMEWORK }}
    - name: Upload Artifacts
      if: startsWith(github.ref, 'refs/pull') || github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Create a Release
      if: github.event_name == 'pull_request' && github.ref == 'refs/heads/master'
      run: echo 'release placeholder'
  deploy-to-staging:
    if: github.event_name == 'pull_request'
    environment: Staging
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Staging
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy-to-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment: Production
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Production
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_NAME }}Prod
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Open Issue
      if: failure() && github.event_name == 'pull_request'
      run: echo 'open issue if there are any failures | placeholder'
